<a href="https://colab.research.google.com/github/mirpouya/Basics-of-ML/blob/main/02_Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array((1,2,3,4))
b

array([1, 2, 3, 4])

In [5]:
type(b)

numpy.ndarray

In [6]:
# data types in a 
a.dtype

dtype('int64')

In [7]:
c = np.array([1,2,"ame", 3.14])
c

array(['1', '2', 'ame', '3.14'], dtype='<U32')

In [8]:
c.dtype

dtype('<U32')

In [9]:
arr1 = np.array([[1,2,3,1], [4,5,6,0]])
arr1

array([[1, 2, 3, 1],
       [4, 5, 6, 0]])

In [10]:
arr1.ndim

2

In [11]:
# accessing elements in the array
arr1[0,1]

2

In [12]:
# different dimentsions
arr2 = np.array([[1,2,3], [4,5,6,7]])
arr2

<ipython-input-12-a348b0e4c27a>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr2 = np.array([[1,2,3], [4,5,6,7]])


array([list([1, 2, 3]), list([4, 5, 6, 7])], dtype=object)

In [13]:
print(arr2)

[list([1, 2, 3]) list([4, 5, 6, 7])]


In [15]:
arr2[0][2]

""" now we can't access the item using arr2[1,2]"""

3

In [16]:
# three dimensional array

arr3 = np.array([[[1,2,3], [3,3,3], [0,10,20]], [[1,2,3], [3,3,3], [0,10,20]]])
arr3

array([[[ 1,  2,  3],
        [ 3,  3,  3],
        [ 0, 10, 20]],

       [[ 1,  2,  3],
        [ 3,  3,  3],
        [ 0, 10, 20]]])

In [17]:
arr3.ndim

3

In [18]:
arr3[1,2,1]

10

In [19]:
arr3.shape

(2, 3, 3)

In [20]:
# total number of elemnts

arr3.size

18

In [21]:
# arrange method

arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
arr = np.arange(20,100,2)
arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])