<a href="https://colab.research.google.com/github/mirpouya/Basics-of-ML/blob/main/Intermediate_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.random.randint(0,10, (1,10))
b

array([[1, 2, 1, 8, 9, 5, 7, 5, 8, 1]])

In [ ]:
print("shape of a is {}".format(a.shape))
print("shape of b is {}".format(b.shape))

shape of a is (10,)
shape of b is (1, 10)


In [ ]:
# many functions do not accept inputs with (n,) shape
# one way to deal with that is np.newaxis

c = a[np.newaxis,:]
print("shape of c is {}".format(c.shape))
c

shape of c is (1, 10)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# if we want to get (n,) shape back we can:

c = np.squeeze(c)
print("shape of c is {}".format(c.shape))
c

shape of c is (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# meaning of dimension in numpy

a = np.arange(80).reshape(2,2,5,4)  # this shape has 4 dimensions
print(a)
print("\n number of dimensions is : {}".format(a.ndim))

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]
   [16 17 18 19]]

  [[20 21 22 23]
   [24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]
   [36 37 38 39]]]


 [[[40 41 42 43]
   [44 45 46 47]
   [48 49 50 51]
   [52 53 54 55]
   [56 57 58 59]]

  [[60 61 62 63]
   [64 65 66 67]
   [68 69 70 71]
   [72 73 74 75]
   [76 77 78 79]]]]

 number of dimensions is : 4


In [ ]:
a.sum(axis=0)       # adding all the elements of each blocks row-wise
                    # reduciton of one dimension     

array([[[ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62],
        [ 64,  66,  68,  70],
        [ 72,  74,  76,  78]],

       [[ 80,  82,  84,  86],
        [ 88,  90,  92,  94],
        [ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118]]])

In [ ]:
a.sum(axis=0).shape

(2, 5, 4)

In [ ]:
# numpy is a very fast frameworkd
# you should use the functions of numpy for your computations

n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

%timeit a + b
%timeit np.add(a,b)

1.14 ms ± 27.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.13 ms ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
