<a href="https://colab.research.google.com/github/mirpouya/Basics-of-ML/blob/main/Intermediate_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.random.randint(0,10, (1,10))
b

array([[1, 2, 1, 8, 9, 5, 7, 5, 8, 1]])

In [4]:
print("shape of a is {}".format(a.shape))
print("shape of b is {}".format(b.shape))

shape of a is (10,)
shape of b is (1, 10)


In [6]:
# many functions do not accept inputs with (n,) shape
# one way to deal with that is np.newaxis

c = a[np.newaxis,:]
print("shape of c is {}".format(c.shape))
c

shape of c is (1, 10)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
# if we want to get (n,) shape back we can:

c = np.squeeze(c)
print("shape of c is {}".format(c.shape))
c

shape of c is (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])