<a href="https://colab.research.google.com/github/mirpouya/Basics-of-ML/blob/main/Intermediate_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.random.randint(0,10, (1,10))
b

array([[1, 3, 4, 3, 8, 0, 1, 0, 7, 5]])

In [4]:
print("shape of a is {}".format(a.shape))
print("shape of b is {}".format(b.shape))

shape of a is (10,)
shape of b is (1, 10)


In [5]:
# many functions do not accept inputs with (n,) shape
# one way to deal with that is np.newaxis

c = a[np.newaxis,:]
print("shape of c is {}".format(c.shape))
c

shape of c is (1, 10)


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
# if we want to get (n,) shape back we can:

c = np.squeeze(c)
print("shape of c is {}".format(c.shape))
c

shape of c is (10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# meaning of dimension in numpy

a = np.arange(80).reshape(2,2,5,4)  # this shape has 4 dimensions
print(a)
print("\n number of dimensions is : {}".format(a.ndim))

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]
   [16 17 18 19]]

  [[20 21 22 23]
   [24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]
   [36 37 38 39]]]


 [[[40 41 42 43]
   [44 45 46 47]
   [48 49 50 51]
   [52 53 54 55]
   [56 57 58 59]]

  [[60 61 62 63]
   [64 65 66 67]
   [68 69 70 71]
   [72 73 74 75]
   [76 77 78 79]]]]

 number of dimensions is : 4


In [8]:
a.sum(axis=0)       # adding all the elements of each blocks row-wise
                    # reduciton of one dimension     

array([[[ 40,  42,  44,  46],
        [ 48,  50,  52,  54],
        [ 56,  58,  60,  62],
        [ 64,  66,  68,  70],
        [ 72,  74,  76,  78]],

       [[ 80,  82,  84,  86],
        [ 88,  90,  92,  94],
        [ 96,  98, 100, 102],
        [104, 106, 108, 110],
        [112, 114, 116, 118]]])

In [9]:
a.sum(axis=0).shape

(2, 5, 4)

In [10]:
# numpy is a very fast frameworkd
# you should use the functions of numpy for your computations

n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

%timeit a + b
%timeit np.add(a,b)

2.66 ms ± 385 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.75 ms ± 309 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
# working with dimensions

a = np.random.rand(1000).reshape(5,4,2,5,5)
a.shape

(5, 4, 2, 5, 5)

In [12]:
b = a.sum(axis=3)
b.shape

(5, 4, 2, 5)

In [21]:
a = np.arange(10)
b = np.ones(10)

print("a is : {}".format(a))
print("b is : {}".format(b))

a is : [0 1 2 3 4 5 6 7 8 9]
b is : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
np.add(a,b, out=b)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
z = np.zeros(20)

np.add(a,10, out=z[::2])

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [27]:
z

array([10.,  0., 11.,  0., 12.,  0., 13.,  0., 14.,  0., 15.,  0., 16.,
        0., 17.,  0., 18.,  0., 19.,  0.])

In [29]:
# same operation, different method
# [::2] it means every other elements

z[::2] = a+50
z

array([50.,  0., 51.,  0., 52.,  0., 53.,  0., 54.,  0., 55.,  0., 56.,
        0., 57.,  0., 58.,  0., 59.,  0.])